config/routes.rb
DigitalMinds::Application.routes.draw do
  match '/home' => 'pages#index', :as => :home
  match '/company' => 'pages#company', :as => :company
  match '/team' => 'pages#team', :as => :team
  match '/careers' => 'pages#careers', :as => :careers
  match '/services' => 'pages#services', :as => :services
  match '/contact' => 'pages#contact', :as => :contact
  root :to => 'pages#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def services
  end
  
  def company
  end
  
  def careers
  end
  
  def team
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Digital Mind Technologies | Big Data | Business Intelligence | Analytics
    = favicon_link_tag
    = stylesheet_link_tag 'application.css', :media => 'screen, projection'
    = csrf_meta_tag
    = javascript_include_tag 'application'
  %body
    .navbar
      .navbar-inner
        .container
          .logo-container
            %a{:href => root_url}
              = image_tag('logo.png', :size => '386x98', :style => "margin-left: 18px;")
          %ul{:class => 'nav btn-toolbar', :style => "margin-left: 58px"}
            = render 'shared/links'
          .social{:class => 'pull-left'}
            = link_to(image_tag('twitter_logo.png'), 'https://twitter.com/#!/digitalmindtech')
            = link_to(image_tag('facebook_logo.png'), 'http://www.facebook.com/pages/Digital-Mind-Technology/183345741793321')
    .container.main
      .notice-area
        = render 'shared/flashes'
      = yield
    .footer
      %hr
      .center
        %span{:class => 'badge badge-info'} 
          &copy; 2012. Digital Mind Technologies Inc. All rights reserved.
    = render 'shared/contact'

app/views/pages/careers.html.haml
.hero-unit
  %h2.center
    Join our exciting team
  %br
  .thumbnail{:class => 'center'}
    = image_tag('careers.jpg', :size => '940x300')
  %br
  %p
    We believe in hiring long and everlasting assets to our company. Working with Digital Mind affords you with a certainty of a successful career around the belief of growth across boundaries. Our commitment to individual choice lets you customize aspects of your career path, your educational opportunities and your benefits. How to improve our business and your clients’ will be heard.
  %br
  %h6 Who we are?
  %p
    A company established to be the Client's problem solving experts. A place to share your open ideas to revamp the existing old technologies in the industry. An institution where investments are made on the resources for their continuous skill and knowledge developments.
  %br
  %h6 Why should you join us?
  %p
    We’re growing quickly, expanding rapidly around the globe, resolving new challenges or problems for clients, and opening new frontiers to explore. We're always looking for how clients can create more innovative ways of doing business, leverage advanced technologies and transform their operations in advance of any economic eventuality.
  %br
  %h6 What we offer?
  %ul.offer-list
    %li Compensation on par with Industry standards
    %li Broad exposure to latest technology skills
    %li Challenging global opportunities
    %li Horizontal and vertical domain experience 
    %li Paid time off
    %li Flexible Work hours
    %li Work life Balance
  %br
  %h6 Seeking Big Data and BI Talent
  %p
    We are always looking for dynamic and motivated architects, senior and junior engineers with specific focus on Big Data and BI technologies like Hadoop, Microsoft Business Intelligence, Cognos, Informatica, Oracle and Microstrategy. The ideal candidate would have specific deep expertise on one or more of these platforms and bring in sound technical and analytical skills, ability to learn and embrace exciting new technologies in the big data space.
  %p
    If you are not a one in a thousand but with a clear mind, innovative ideas and positive energy looking for THE opening which you believe will shape up your career in the way you dreamt and believe that you have the right energy to join other leaders in this Industry, send us your resume to 
    = mail_to('hr@digitalmindtech.com')

app/views/pages/company.html.haml
.hero-unit
  %h2.center
    About Digital Mind
  %br
  .thumbnail{:class => 'center'}
    = image_tag('about_us.jpg', :size => '940x300')
  %p
  %p
    Digital Mind provides experts in Business Intelligence, Big Data, Analytical report development, Cloud Computing and Mobile Application Development to empower your organization by transforming available data into insights resulting in an indisputable bottom line impact.
  %p
    Our Chief Technology Architects and Implementers have vast experience with different technologies as mentioned below. In case, the technology that you are looking for is not present in the list, please contact us. We are confident that we may have the skill set that you’re looking for.
.row
  .span3
    %h6 Databases
    %ul.techs
      %li IBM Netezza
      %li Oracle
      %li Microsoft SQL Server
      %li Cloudera
      %li DATAllegro (Microsoft)
      %li Hadoop
      %li HP Vertica
      %li Hortonworks
      %li IBM DB2
      %li Informix
      %li ParAccel
      %li Sybase/Sybase IQ
      %li Teradata
  .span3
    %h6 Master Data Management
    %ul.techs
      %li IBM InfoSphere Master Data Management
      %li Informatica MDM
      %li Kalido
      %li Oracle MDM
      %li SAP MDM
      %li Data Modeling
      %li Composite Studio
      %li CA Erwin Data Modeler
      %li ER/Studio (Embarcadero)
      %li Oracle
      %li Data Integration/Data Management
      %li Ab Initio
      %li Composite
      %li DT/Studio (Embarcadero)
      %li IBM InfoSphere Datastage
      %li Informatica
      %li Oracle Warehouse Builder
      %li Talend 
  .span3
    %h6 Information Delivery
    %ul.techs
      %li BusinessObjects (SAP)
      %li Cognos (IBM)
      %li Crystal Reports
      %li Hyperion (Oracle)
      %li Microsoft SQL
      %li MicroStrategy
      %li Qlikview
      %li SAS Dataflux 
      %li SPSS
      %li Tableau
      %li SSRS
  .span3
    %h6 Application Development
    %ul.techs
      %li AJAX
      %li ASP
      %li ATG 
      %li BEA WebLogic
      %li C/C++/C#
      %li ColdFusion
      %li CSS
      %li Java/JavaScript/JSP/J2EE
      %li HTML, DHTML, XML, XSL
      %li IBM WebSphere
      %li Microsoft .NET
      %li Perl
      %li PHP
      %li Python
      %li Ruby on Rails
      %li SQL
      %li Windows/Unix

app/views/pages/index.html.haml
= render 'shared/carousel'
.hero-unit
  %p
    %b Digital Mind is focused on elevating the business intelligence and analytical capabilities to a new level by providing solutions and services through Big Data and various cutting-edge emerging information management platforms.
.row
  .span4
    %h6 Big Data Services
    %p
      Today, most of the industries have data many times more than what they had a decade  ago and having a huge challenge in finding ways to leverage their business to drive profitability and growth.
    = link_to('View more', services_url)
  .span4
    %h6 Business Intelligence Services
    %p
      The business environment today is more dynamic than ever and needs to be leveraging technology for sound decision making. The tools available today propel business strategizing to newer terrains.
    = link_to('View more', services_url)
  .span4
    %h6 Information Delivery/Analytics
    %p
      Our experts deliver information delivery architecture and design of the user interface, report design, data provisioning, statistical modeling and deep analytics to drive your business strategy. 
    = link_to('View more', services_url)

    

app/views/pages/services.html.haml
.hero-unit.services
  %h2.center
    Services we provide
  %br
  %h6 Big Data Services
  %p
    Today, most of the industries have data many times more than what they had a decade  ago and having a huge challenge in finding ways to leverage their business to drive profitability and growth.
  %p
    In a fast growing business environment, with rapid changes, organizations are faced with enormous competitive challenges. Reactive business intelligence and dashboard reporting alone is no longer sufficient for the enterprise to stay in the competition. To stay competitive, the organizations need to start leveraging the transformational power of data to generate reports internally or externally and become more capable in anticipating market demands, predicting business outcomes and responding to events in real time before opportunities are missed.
  %p
    Digital Mind provides experts to build business aligned solutions, development and other services from strategy to realization, enabling enterprises to develop a data management system in an integrated cohesive environment by combining current BI platforms with the Hadoop ecosystem and all other big data technologies.
  %br
  %h6 Business Intelligence and Data Warehousing services
  %p
    The business environment today is more dynamic than ever, with mergers & acquisitions and consolidation & regulatory changes. To succeed, an enterprise needs to develop an ability to sense these changes, respond quickly and dynamically. 
  %p
    Organizations that leverage business analytics to derive insight from their data assets outperform their competitors by making better real-time decisions which drive better business outcomes.
  %p
    Digital Mind helps organizations to integrate data from across the enterprise and deliver user friendly reporting and analytical capability using an agile methodology. This empowers organizations to execute real-time analytics, derive valuable insights, engage customers within context, and quickly react to market opportunity.
  %p
    Our Data Integration experts focus on building scalable and high-performance data acquisition from source systems across the enterprise.  It includes data capacity planning, data integration design, architecture, data validation, performance, security and disaster recovery. We leverage our best practices, accelerators, reference architecture and frameworks in a manner that speeds up development and time to delivery, without forsaking the integrity of the delivered system.
  %p
    Our Data Warehousing experts deliver data architecture, data modeling, metadata architecture design and design & development for operational data store, data marts and other data repositories.
  %br
  %h6 Information Delivery and Analytics
  %p 
    Our experts deliver information delivery architecture and design of the user interface, report design, data provisioning, statistical modeling and analytics. 
  %br
  %h6 Cloud Computing Services
  %p 
    We address various aspects of cloud development, cloud adoption by providing professional services to companies with business agility, while reducing total cost of ownership. Our Services for the Cloud provide you with complete ownership of Cloud development and adoption life cycle and are backed by our best-in-class partners. 
  %br
  %h6 Mobile Services
  %p 
    Our Experts help you to leverage the benefits of mobility to connect with your employees, partners and customers anytime, anywhere.
  %p
    Digital Mind will transform customer service into contextual interactions. To create mobile systems which are deeply integrated into an existing enterprise infrastructure, pose significant development and integration challenges. We are in the process of forming strong partnerships with major mobile platform vendors and major enterprise software vendors to provide our customers with a highly knowledgeable service in mobile application development to resolve challenges.
  %br
  %p
    If you are willing to consider us for your next big project, Please 
    = link_to("write", '#contact', "data-toggle" => "modal")
    to us.

app/views/pages/team.html.haml
.hero-unit.team
  %h2.center
    Our Team
  %br
  %h6 Narayanan Ramasamy
  %br
  %p
    Narayanan Ramasamy is the Chief Executive Officer (CEO) and Managing Director of the company. Narain has more than 13 years of data warehousing and analytics experience at company like  QWEST Communication Inc, The Nielsen Company and Sears Holding Corporation, Narain leads Digital Mind  across every aspect, including driving the company's strategic vision and providing executive level support and guidance across Digital Mind’s client base. Narain personifies Digital Mind’s commitment to customer satisfaction and high quality of deliverables. Through his vast experience in a variety of operating roles across Digital Mind, he has built a reputation in the IT services industry for his exceptional ability to build and grow new businesses and nurture long-term relationships.

app/views/shared/_carousel.html.haml
#walkthru-carousel{:class => 'carousel slide'}
  .carousel-inner
    %div{:class => 'active item'}
      = image_tag('cloud_computing.jpg', :size => '940x340')
      .carousel-caption
        %h4.center We address various aspects of cloud development, cloud adoption by providing professional services
    %div{:class => 'item'}
      = image_tag('mobile_dev.jpg', :size => '940x340')
      .carousel-caption
        %h4.center Our professionals help you in bringing computing and data to your “point of need” in your enterprise business processes
    %div{:class => 'item'}
      = image_tag('big_data.jpg', :size => '940x340')
      .carousel-caption
        %h4.center Most of the industries have data many times, more than what they had a decade ago
    %div{:class => 'item'}
      = image_tag('analytics.jpg', :size => '940x340')
      .carousel-caption
        %h4.center We provide experts in Business Intelligence and Data Warehousing services
    %div{:class => 'item'}
      = image_tag('information_del.jpg', :size => '940x340') 
      .carousel-caption
        %h4.center Information Delivery & Analytics experts help your enterprise get agile, adaptable and more efficient reporting

app/views/shared/_contact.html.haml
#contact{:class => 'modal hide fade', :url => contact_url}
  .modal-header
    %h1 Get in touch with us
  .modal-body
    %h6.center
      Our Address
    %p.center
      Digital Mind Technologies Corporate Headquarters
      %br
      2500, West Higgins Road, Suite 1273
      %br
      Hoffman Estates, Illinois, USA - 60169
      %br
      Phone: +1.815.980.8749 Fax: +1.847.598.1106
    .form
      %p
        %br
      = form_tag(contact_path, :id => 'contact-form') do
        %label.label Name*
        = text_field_tag 'name'      
        %label.label Email*
        = text_field_tag 'email'
        %label.label This is about
        = select_tag 'about', options_for_select(['New opportunity', 'Questions', 'Other'])
        %label.label
        = text_area_tag 'comments', nil, :placeholder => 'Use this space to reach out to us about a new opportunity or if you want ask us as general question'
  .modal-footer
    .loader{:style => 'display: none;', :class => 'pull-left'}
      = image_tag('loader.gif')
    = link_to('Submit', '#', :id => 'contact-submit', :class => 'btn btn-primary btn-large pull-left')

app/views/shared/_flashes.html.haml
- flash.each do |name, msg|
  - unless msg.blank?
    - case name
      - when :alert, :error then
        = content_tag :div, msg, :class => "alert alert-error"
      - when :success then
        = content_tag :div, msg, :class => "alert alert-success"
      - when :warning then
        = content_tag :div, msg, :class => "alert alert-warning"
      - when :notice then
        = content_tag :div, msg, :class => "alert alert-info"
      - else 
        = content_tag :div, msg, :class => "alert alert-info"

app/views/shared/_links.html.haml
%li= link_to("Home", root_url, :class => 'btn btn-large')
%li= link_to("Services", services_url, :class => 'btn btn-large')
%li= link_to("About us", company_url, :class => 'btn btn-large')
%li= link_to("Careers", careers_url, :class => 'btn btn-large')
%li= link_to("Contact Us", '#contact', "data-toggle" => "modal", :class => 'btn btn-large')